openapi: 3.0.0
info:
     title: Triathlon Tracker Service
       description: "This is the API definition for the Triathlon Tracker Service."
       version: 1.0.0

servers:
  - url: http://localhost:3000

tags:
  - name: Playlists
    description: Create, view, and update playlists

  - name: Songs
    description: View and add songs to playlists

       - name: Triathlon
         descriptions: Create, view, and update triathlon workouts

       paths:

         /workouts:
           post:
             tags:
               - Triathlon
             summary: Create a new completed triathlon workout log (CreateWorkoutLambda)
             requestBody:
               content:
                 application/json:
                   schema:
                     type: object
                     properties:
                       customerId:
                         type: string
                       date:
                         type: string
                       workoutType:
                         type: enum
                       durationInHours:
                         type: integer
                       durationInMin:
                         type: integer
                       durationInSeconds:
                         type: integer
                       distance:
                         type: double
             responses:
               "200":
                 description: A triathlon workout log object
                 content:
                   application/json:
                     schema:
                       type: object
                       properties:
                         workoutId:
                           type: string
                         userName:
                           type: string
                         date:
                           type: string
                         workoutType:
                           type: enum
                         durationInHours:
                           type: integer
                         durationInMin:
                           type: integer
                         durationInSeconds:
                           type: integer
                         distance:
                           type: double

         /playlists:
           post:
             tags:
