openapi: 3.0.0
info:
  title: Triathlon Tracker Service
  description: "This is the API definition for the Triathlon Tracker Service."
  version: 1.0.0

servers:
  - url: http://localhost:3000

tags:
  - name: Triathlon
    description: Create, view, and update triathlon workouts

paths:

  /workouts:
    post:
      tags:
        - Triathlon
      summary: Create a new completed triathlon workout log (CreateWorkoutLambda)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  type: string
                  example: "test@test.com"
                date:
                  type: string
                  format: date
                workoutType:
                  type: string
                  example: "RUNNING"
                durationInHours:
                  type: string
                  description: The duration in hours
                  pattern: '^[0-9]+$'
                  example: "5"
                durationInMinutes:
                  type: string
                  pattern: '^[0-9]+$'
                  example: "20"
                durationInSeconds:
                  pattern: '^[0-9]+$'
                  type: string
                  example: "30"
                distance:
                  type: string
                  example: "20"
      responses:
        "200":
          description: A triathlon workout log object
          content:
            application/json:
              schema:
                type: object
                properties:
                  workoutId:
                    type: string
                  customerId:
                    type: string
                  customerName:
                    type: string
                  date:
                    type: string
                    format: date
                  workoutType:
                    type: string
                    example: "RUNNING"
                  durationInHours:
                    type: string
                    example: "20"
                  durationInMinutes:
                    type: string
                    example: "20"
                  durationInSeconds:
                    type: string
                    example: "20"
                  distance:
                    type: string
                    example: "20"

  /workouts/{workout_id}:
    delete:
      summary: Delete a workout with a workout ID
      tags:
        - Triathlon
      parameters:
        - name: workout_id
          in: path
          description: ID of the workout to delete
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A success message indicating the workout was deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  workoutId:
                    type: string
                    example: "abc1234a"
        "400":
          description: An error indicating the workout could not be deleted

  /workouts/customers/{customerId}:
    get:
      summary: Get full workout history by customer ID
      tags:
        - Triathlon
      parameters:
        - name: customerId
          in: path
          description: ID of the customer to retrieve workout history
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A list of workouts for the specified customer ID
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    workoutId:
                      type: string
                    customerId:
                      type: string
                    customerName:
                      type: string
                    date:
                      type: string
                      format: date
                    workoutType:
                      type: string
                    durationInHours:
                      type: string
                    durationInMinutes:
                      type: string
                    durationInSeconds:
                      type: string
                    distance:
                      type: string
        "400":
          description: An error indicating the workout history could not be retrieved

  /workouts/type/{workoutType}/customers/{customerId}/recent/:
    get:
      summary: Get the most recent workout of a specific type for a customer
      tags:
        - Triathlon
      parameters:
        - name: workoutType
          in: path
          description: Type of workout to retrieve (e.g. RUNNING, SWIMMING, BIKING)
          required: true
          schema:
            type: string
        - name: customerId
          in: path
          description: ID of the customer to retrieve the workout for
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The most recent workout of the specified type for the customer
          content:
            application/json:
              schema:
                type: object
                properties:
                  workoutId:
                    type: string
                  customerId:
                    type: string
                  customerName:
                    type: string
                  date:
                    type: string
                    format: date
                  workoutType:
                    type: string
                  durationInHours:
                    type: string
                  durationInMinutes:
                    type: string
                  durationInSeconds:
                    type: string
                  distance:
                    type: string
        "400":
          description: An error indicating the recent workout could not be retrieved